#!/usr/bin/lua

function atwork() 
   return (os.execute("ping 10.7.1.24 -c 1 -w 1 > /dev/null"))
end

function sleep(n)
   os.execute("sleep "..n)
end


luasql = require "luasql.mysql"
env = assert (luasql.mysql())
con = assert (env:connect("timetrack","root", "12345678"))

if (atwork() == true) then
    con:execute("insert into daily values(now());")
end

